project:
  type: website
  execute-dir: project
  output-dir: docs

execute:
  freeze: auto
  engine: knitr
  port: 8877
  cache: true

website:
  title: "Hubert Baechli: ICMB portfolio"
  back-to-top-navigation: true
  page-navigation: true

  navbar:
    left:
      - href: index.qmd
        text: About
  sidebar:
    style: "docked"
    search: true
    collapse-level: 1
    contents:
      - index.qmd
      - hw1/index.qmd
      - section:
        href: hw2/index.qmd
        contents:
        - hw2/sketchbook.qmd
        - hw2/notebook_final3.qmd
      - section:
        href: Snippets/index.qmd
        contents:
        - Snippets/BetaDistribution.qmd
      - section:
        href: Project/index.qmd
        contents:
        - Project/sketchbook00.qmd

format:
  html:
    theme: cosmo
    toc: true
    code-link: true
    code-copy: true
    code-tools: true
    code-fold: true
    code-overflow: wrap
    page-layout: full
    css: styles.css

editor: visual
