---
title: "Assignment 2: <br>Economic Simulation"
author: "Hubert Baechli"
---

# Tasks

The second assignment has 2 components and you have the next 2 weeks to work on it. 

-   Replicate the first simulation from <https://github.com/norvig/pytudes/blob/main/ipynb/Economics.ipynb#js-repo-pjax-container> in R

-   Attempt to understand why the model produces such inequality by “playing with it”. You would have to first think about why it might do this, describe your thought process, and then change parts of the code, add new visualizations, etc, to see if you can explain why it behaves the way it does. This is going to be quite challenging and creative

# Instructions

To do this assignment and submit it you have to:

1.  make a new folder "hw2" in your existing project folder

2.  create a new quarto document, for example "index.qmd" in the "hw2" folder

3.  add "- hw2/index.qmd" to the "\_quarto.yml" file sidebar section

4.  write your thoughts as text in the document, r code in R chunks

5.  Render the notebook to run the code and see the results intermixed with your description

6.  add your new files and commit the to git as you make changes

7.  when you are done with the replication part of the assignment, push your changes to github - you will be able to see your results on your github website. Try to finish this first by next week

8.  resume from step 4 for the second part of the assignment to explore the model
